name: Run Smoke Tests and Deploy to Render

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y jq  # Needed for JSON parsing in smoke-test.sh

      - name: Start Flask API
        run: |
          python app.py &
          sleep 5  # Give time for the API to start

      - name: Run Smoke Test
        run: bash testing/smoke-test.sh

  deploy:
    needs: test  # Only deploy if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "srv-cvismh2dbo4c739brh40",
              "branch": "master"
            }' \
            https://api.render.com/v1/services/srv-cvismh2dbo4c739brh40/deploys

